NAME=sudo
VERSION=1.9.17p2
LICENSE=ISC
ARCHES=x86_64
STATUS_x86_64=supported
STATUS_aarch64=blocked-by-package
KERNEL_CAPS=proc.pid.stat setuid setgid supplementary_groups tty
OUTPUTS=sudo
SETUID=sudo
