NAME=tinyx
VERSION=feab72ca891bc04b18763763e15ee4e532369cdf
LICENSE=GPL-3.0-only
ARCHES=x86_64
STATUS_x86_64=supported
STATUS_aarch64=blocked-by-package
KERNEL_CAPS=fb,evdev,mmap,unix-sockets,sysv-shm
DEPENDS=xorgproto xtrans libxau libxdmcp libx11 libxext libxi libxtst zlib freetype libfontenc libxfont
OUTPUTS=Xfbdev
