#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""ISD package extras + applet extras (.isdconfig) — stdlib only.

Commands: defconfig | show | set KEY=VAL | validate | menu

make isdconfig → interactive menu (toggle y/n, save, validate).
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CFG = ROOT / ".isdconfig"

# Always-on core (cannot be disabled).
FORBIDDEN_DISABLE = ("BUSYBOX", "RUNIT")

# Optional package extras (packages/<name>/).
EXTRAS = (
    "NANO",
    "NCURSES",
    "OPENDOAS",
    "TINYCC",
    "GNUMAKE",
    "DOOM",
    "IV",
    "PACK_EXTRACT",
)

# BusyBox applet extras — link /bin/<applet> when =y (binary must include applet).
# short → applet name
APPLETS: dict[str, str] = {
    "TOP": "top",
}

# Reserved for extras that need a non-lowercase package dir name.
# DOOM → packages/doom/ (packaged); keep map empty unless a rename is needed.
FUTURE_PACKAGES: dict[str, str] = {
    "PACK_EXTRACT": "pack-extract",
}

# If KEY=y, ensure each dep is y (or reject).
AUTO_DEPS = {
    "NANO": ("NCURSES",),
}

CORE_DEFAULTS = {k: "y" for k in FORBIDDEN_DISABLE}

# Sensible test-distro defaults: common extras on; futures off.
# TINYCC/GNUMAKE stay optional here — desktop mandates them via packages.txt.
EXTRA_DEFAULTS = {
    "NANO": "y",
    "NCURSES": "y",
    "OPENDOAS": "y",
    "TINYCC": "n",
    "GNUMAKE": "n",
    "DOOM": "n",
    "IV": "n",
    "PACK_EXTRACT": "n",
}
APPLET_DEFAULTS = {k: "y" for k in APPLETS}


def cfg_path(explicit: str | None = None) -> Path:
    if explicit:
        return Path(explicit)
    env = os.environ.get("ISD_CONFIG")
    if env:
        return Path(env)
    return DEFAULT_CFG


def parse_cfg(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.is_file():
        return data
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, val = line.split("=", 1)
        data[key.strip()] = val.strip()
    return data


def write_cfg(path: Path, data: dict[str, str]) -> None:
    keys = (
        [f"CONFIG_PKG_{k}" for k in FORBIDDEN_DISABLE]
        + [f"CONFIG_PKG_{k}" for k in EXTRAS]
        + [f"CONFIG_APPLET_{k}" for k in APPLETS]
    )
    lines = [
        "# ISD package extras (.isdconfig) — generated by scripts/isdconfig.py",
        "# Core busybox/runit always on. Profile packages.txt = mandatory set.",
        "# CONFIG_PKG_* = optional packages; CONFIG_APPLET_* = BusyBox links.",
        "",
    ]
    for key in keys:
        if key.startswith("CONFIG_PKG_"):
            short = key[len("CONFIG_PKG_") :]
            val = data.get(
                key,
                CORE_DEFAULTS.get(short, EXTRA_DEFAULTS.get(short, "n")),
            )
        else:
            short = key[len("CONFIG_APPLET_") :]
            val = data.get(key, APPLET_DEFAULTS.get(short, "n"))
        lines.append(f"{key}={val}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def ensure_defaults(data: dict[str, str]) -> dict[str, str]:
    out = dict(data)
    for k, v in CORE_DEFAULTS.items():
        out.setdefault(f"CONFIG_PKG_{k}", v)
    for k, v in EXTRA_DEFAULTS.items():
        out.setdefault(f"CONFIG_PKG_{k}", v)
    for k, v in APPLET_DEFAULTS.items():
        out.setdefault(f"CONFIG_APPLET_{k}", v)
    return out


def pkg_enabled(data: dict[str, str], short: str) -> bool:
    return data.get(f"CONFIG_PKG_{short}", "n").lower() in ("y", "yes", "1")


def applet_enabled(data: dict[str, str], short: str) -> bool:
    return data.get(f"CONFIG_APPLET_{short}", "n").lower() in ("y", "yes", "1")


def pkg_dirname(short: str) -> str:
    """CONFIG_PKG_FOO → packages/<dir> name."""
    if short in FUTURE_PACKAGES:
        return FUTURE_PACKAGES[short]
    return short.lower()


def recipe_ready(short: str) -> bool:
    d = pkg_dirname(short)
    return (ROOT / "packages" / d / "build.sh").is_file()


def find_doom_iwad() -> Path | None:
    """Locate an IWAD (same rules as scripts/find-doom-iwad.sh)."""
    script = ROOT / "scripts" / "find-doom-iwad.sh"
    if not script.is_file():
        iwad = os.environ.get("ISD_DOOM_IWAD", "").strip()
        if iwad and Path(iwad).is_file():
            return Path(iwad)
        return None
    import subprocess

    try:
        proc = subprocess.run(
            ["bash", str(script)],
            capture_output=True,
            text=True,
            check=False,
            env=os.environ.copy(),
        )
    except OSError:
        return None
    path = (proc.stdout or "").strip()
    if proc.returncode == 0 and path and Path(path).is_file():
        return Path(path)
    return None


def refuse_enable_pkg(short: str) -> str | None:
    """If short cannot be enabled (=y), return a warning; else None."""
    if short in FORBIDDEN_DISABLE:
        return None
    if short not in EXTRAS:
        return f"unknown package CONFIG_PKG_{short}"
    d = pkg_dirname(short)
    if not recipe_ready(short):
        return (
            f"CONFIG_PKG_{short}=y ignored: packages/{d}/ not packaged yet "
            f"(forced n). Interim: IR0_LEGACY_USERSPACE=1 make load-userspace-devtools"
        )
    if short == "DOOM":
        if find_doom_iwad() is None:
            return (
                "CONFIG_PKG_DOOM=y ignored: no IWAD found "
                "(set ISD_DOOM_IWAD or place DOOM1.WAD in ../universal-doom/) "
                "(forced n)"
            )
    return None


def scrub_unready_pkgs(data: dict[str, str]) -> list[str]:
    """Force =n for packages that cannot be built; return warning lines."""
    warnings: list[str] = []
    for short in EXTRAS:
        if not pkg_enabled(data, short):
            continue
        msg = refuse_enable_pkg(short)
        if msg:
            data[f"CONFIG_PKG_{short}"] = "n"
            warnings.append(f"⚠ {msg}")
    return warnings


def _normalize_assignment(item: str) -> tuple[str, str, str] | None:
    """Return (kind, short, val) where kind is 'PKG' or 'APPLET'."""
    if "=" not in item:
        return None
    key, val = item.split("=", 1)
    key = key.strip()
    val = val.strip().lower()
    if val not in ("y", "n"):
        return None
    upper = key.upper()
    if upper.startswith("CONFIG_PKG_"):
        short = upper[len("CONFIG_PKG_") :]
        return ("PKG", short, val)
    if upper.startswith("CONFIG_APPLET_"):
        short = upper[len("CONFIG_APPLET_") :]
        return ("APPLET", short, val)
    if upper.startswith("PKG_"):
        return ("PKG", upper[len("PKG_") :], val)
    if upper.startswith("APPLET_"):
        return ("APPLET", upper[len("APPLET_") :], val)
    # Bare short name: prefer PKG if known, else APPLET.
    short = upper
    if short in FORBIDDEN_DISABLE or short in EXTRAS:
        return ("PKG", short, val)
    if short in APPLETS:
        return ("APPLET", short, val)
    return ("PKG", short, val)


def cmd_defconfig(path: Path, force: bool) -> int:
    if path.is_file() and not force:
        print(f"  CONFIG    {path} already present (use --force to reset)")
        return 0
    data = ensure_defaults({})
    write_cfg(path, data)
    print(f"  CONFIG    wrote {path}")
    return 0


def cmd_show(path: Path) -> int:
    data = ensure_defaults(parse_cfg(path))
    print(f"# {path}")
    print("# packages")
    for k in list(FORBIDDEN_DISABLE) + list(EXTRAS):
        key = f"CONFIG_PKG_{k}"
        print(f"{key}={data.get(key, 'n')}")
    print("# applets (BusyBox hardlinks)")
    for k in APPLETS:
        key = f"CONFIG_APPLET_{k}"
        print(f"{key}={data.get(key, 'n')}  → /bin/{APPLETS[k]}")
    return 0


def cmd_set(path: Path, assignments: list[str]) -> int:
    data = ensure_defaults(parse_cfg(path))
    for item in assignments:
        parsed = _normalize_assignment(item)
        if parsed is None:
            print(f"✗ expected KEY=y|n, got {item!r}", file=sys.stderr)
            return 1
        kind, short, val = parsed
        if kind == "PKG":
            key = f"CONFIG_PKG_{short}"
            if short in FORBIDDEN_DISABLE and val == "n":
                print(
                    f"✗ cannot disable CONFIG_PKG_{short} (core package)",
                    file=sys.stderr,
                )
                return 1
            if short not in FORBIDDEN_DISABLE and short not in EXTRAS:
                print(f"✗ unknown package key CONFIG_PKG_{short}", file=sys.stderr)
                return 1
            if val == "y":
                msg = refuse_enable_pkg(short)
                if msg:
                    print(f"⚠ {msg}", file=sys.stderr)
                    val = "n"
            data[key] = val
            if val == "y" and short in AUTO_DEPS:
                for dep in AUTO_DEPS[short]:
                    data[f"CONFIG_PKG_{dep}"] = "y"
        else:
            if short not in APPLETS:
                print(f"✗ unknown applet key CONFIG_APPLET_{short}", file=sys.stderr)
                return 1
            data[f"CONFIG_APPLET_{short}"] = val
    for w in scrub_unready_pkgs(data):
        print(w, file=sys.stderr)
    write_cfg(path, data)
    print(f"  CONFIG    updated {path}")
    return 0


def cmd_validate(path: Path, profile: str) -> int:
    data = ensure_defaults(parse_cfg(path))
    errors: list[str] = []
    changed = False

    for short in FORBIDDEN_DISABLE:
        if not pkg_enabled(data, short):
            errors.append(
                f"✗ CONFIG_PKG_{short}=n is forbidden (core package; "
                f"leave CONFIG_PKG_{short}=y)."
            )

    for short, deps in AUTO_DEPS.items():
        if pkg_enabled(data, short):
            for dep in deps:
                if not pkg_enabled(data, dep):
                    errors.append(
                        f"✗ CONFIG_PKG_{short}=y requires CONFIG_PKG_{dep}=y "
                        f"(auto-dep)."
                    )

    # Auto-downgrade unready extras so first-boot / validate-config cannot wedge.
    for w in scrub_unready_pkgs(data):
        print(w, file=sys.stderr)
        changed = True

    for short in EXTRAS:
        if not pkg_enabled(data, short):
            continue
        dirname = pkg_dirname(short)
        pkg_dir = ROOT / "packages" / dirname
        if not pkg_dir.is_dir() or not (pkg_dir / "build.sh").is_file():
            errors.append(
                f"✗ CONFIG_PKG_{short}=y but packages/{dirname}/ missing "
                f"(internal: scrub failed)."
            )

    for short, applet in APPLETS.items():
        if not applet_enabled(data, short):
            continue
        if short == "TOP":
            frag = ROOT / "packages" / "busybox" / "ir0_full.config"
            if frag.is_file() and "CONFIG_TOP=y" not in frag.read_text(encoding="utf-8"):
                errors.append(
                    f"✗ CONFIG_APPLET_TOP=y but packages/busybox/ir0_full.config "
                    f"lacks CONFIG_TOP=y (rebuild busybox after enabling TOP)."
                )

    if changed and path.is_file():
        write_cfg(path, data)
        print(f"  CONFIG    scrubbed unready extras → {path}")

    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1

    print(f"✓ isdconfig validate OK PROFILE={profile}")
    return 0


def _prompt_yn(inp, out, prompt: str, current: str) -> str:
    cur = current.lower() if current.lower() in ("y", "n") else "n"
    while True:
        out.write(f"{prompt} [{cur}] ")
        out.flush()
        line = inp.readline()
        if not line:
            return cur
        ans = line.strip().lower()
        if ans == "":
            return cur
        if ans in ("y", "n"):
            return ans
        if ans in ("yes", "true", "1"):
            return "y"
        if ans in ("no", "false", "0"):
            return "n"
        out.write("  enter y or n (empty keeps current)\n")
        out.flush()


class _Closer:
    def __init__(self, *files) -> None:
        self._files = files

    def close(self) -> None:
        for f in self._files:
            try:
                f.close()
            except OSError:
                pass


def _open_menu_streams():
    """Return (inp, out, closer) for the interactive menu.

    Prefer stdin/stdout when they are TTYs (works when /dev/tty is ENXIO,
    e.g. some IDE/WSL sessions). Else try /dev/tty. closer may be None.
    """
    if sys.stdin.isatty() and sys.stdout.isatty():
        return sys.stdin, sys.stdout, None
    try:
        tty = open("/dev/tty", "r+", encoding="utf-8", errors="replace")
        return tty, tty, tty
    except OSError:
        pass
    try:
        tin = open("/dev/tty", "r", encoding="utf-8", errors="replace")
        tout = open("/dev/tty", "w", encoding="utf-8", errors="replace")
        return tin, tout, _Closer(tin, tout)
    except OSError:
        pass
    return None, None, None


def cmd_menu(path: Path, profile: str) -> int:
    """Interactive toggle for extras; saves and validates."""
    data = ensure_defaults(parse_cfg(path))

    inp, out, closer = _open_menu_streams()
    if inp is None or out is None:
        print(
            "✗ isdconfig menu needs an interactive terminal "
            "(stdin/stdout TTY or /dev/tty).\n"
            "  From a real shell:\n"
            "    make isdconfig PROFILE=minimal\n"
            "  Non-interactive:\n"
            "    python3 scripts/isdconfig.py set CONFIG_PKG_NANO=y\n"
            "    python3 scripts/isdconfig.py set CONFIG_APPLET_TOP=y\n"
            "    python3 scripts/isdconfig.py show",
            file=sys.stderr,
        )
        return 1

    try:
        out.write("ISD test-distro software (toggle y/n)\n")
        out.write(f"Config: {path}\n")
        out.write(f"Profile: {profile}\n")
        out.write("Core busybox + runit are always on.\n")
        out.write("Empty answer keeps the current value.\n\n")
        out.flush()

        out.write("--- packages ---\n")
        for short in EXTRAS:
            key = f"CONFIG_PKG_{short}"
            cur = data.get(key, EXTRA_DEFAULTS.get(short, "n"))
            note = ""
            if not recipe_ready(short):
                note = f"  (not packaged: packages/{pkg_dirname(short)}/ — cannot enable)"
                cur = "n"
            elif short in FUTURE_PACKAGES:
                note = f"  (packages/{FUTURE_PACKAGES[short]}/)"
            if short in AUTO_DEPS:
                note += f"  [deps: {', '.join(AUTO_DEPS[short])}]"
            out.write(f"  {key}{note}\n")
            out.flush()
            if not recipe_ready(short):
                out.write(f"  {short} [n] (skipped — not packaged)\n")
                out.flush()
                data[key] = "n"
                continue
            data[key] = _prompt_yn(inp, out, f"  {short}", cur)
            if data[key] == "y":
                msg = refuse_enable_pkg(short)
                if msg:
                    out.write(f"    ⚠ {msg}\n")
                    out.flush()
                    data[key] = "n"
            if data[key] == "y" and short in AUTO_DEPS:
                for dep in AUTO_DEPS[short]:
                    data[f"CONFIG_PKG_{dep}"] = "y"
                    out.write(f"    → auto-enabled CONFIG_PKG_{dep}=y\n")
                    out.flush()

        out.write("\n--- BusyBox applets ---\n")
        for short, applet in APPLETS.items():
            key = f"CONFIG_APPLET_{short}"
            cur = data.get(key, APPLET_DEFAULTS.get(short, "n"))
            out.write(f"  {key} → /bin/{applet}\n")
            out.flush()
            data[key] = _prompt_yn(inp, out, f"  {short}", cur)

        out.write("\n")
        out.flush()
        save = _prompt_yn(inp, out, "Save .isdconfig", "y")
        if save != "y":
            out.write("  (discarded)\n")
            out.flush()
            return 0
    finally:
        if closer is not None:
            closer.close()

    write_cfg(path, data)
    print(f"  CONFIG    wrote {path}")
    rc = cmd_validate(path, profile)
    if rc == 0:
        print("")
        print("Next: rebuild the image so packages/applets apply:")
        print(f"  make isd-image PROFILE={profile}")
        print(f"  # or from IR0: make first-boot PROFILE={profile}")
        cmd_show(path)
    return rc


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="ISD .isdconfig helper")
    ap.add_argument(
        "--config",
        default=None,
        help="path to .isdconfig (default: $ISD_CONFIG or repo root)",
    )
    ap.add_argument(
        "--profile",
        default=os.environ.get("PROFILE", "minimal"),
        help="profile name for validate messages",
    )
    sub = ap.add_subparsers(dest="cmd", required=True)

    p_def = sub.add_parser("defconfig", help="write defaults if missing")
    p_def.add_argument(
        "--force", action="store_true", help="overwrite existing config"
    )

    sub.add_parser("show", help="print effective config")
    p_set = sub.add_parser("set", help="set CONFIG_PKG_* / CONFIG_APPLET_*=y|n")
    p_set.add_argument("assignments", nargs="+", help="KEY=VAL …")
    sub.add_parser("validate", help="validate config against recipes")
    sub.add_parser("menu", help="interactive extras menu (TTY)")

    args = ap.parse_args(argv)
    path = cfg_path(args.config)

    if args.cmd == "defconfig":
        return cmd_defconfig(path, args.force)
    if args.cmd == "show":
        return cmd_show(path)
    if args.cmd == "set":
        return cmd_set(path, args.assignments)
    if args.cmd == "validate":
        return cmd_validate(path, args.profile)
    if args.cmd == "menu":
        return cmd_menu(path, args.profile)
    ap.error(f"unknown command {args.cmd}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
